### ISSUE TITLE
Exception undefined in Safari

### ISSUE THREAD

**Issue by rigoneri** [cerner/canadarm#6]
Sometimes standardLogAppender exception param is undefined in Safari, which is causing canadarm to blow up on this line https://github.com/cerner/canadarm/blob/master/build/canadarm.js#L470

Maybe it should check the stack variable defined on line 388? 
Or check if exception is undefined on line 470?

**Comment by garrypolley** [comment]
I'll take a longer look into this later, but here is what is going on at a quick glance. 

https://github.com/cerner/canadarm/blob/master/lib/appender/standard.js#L31 <-- that line actually defines `stack` from `exception.stack` or creates a new one. If `stack` is not defined.

So we are explicitly checking `exception.stack` here: https://github.com/cerner/canadarm/blob/master/lib/appender/standard.js#L113 so that we can be sure the `exception` we use is correct. 

I'll take a further look, but I do not think swapping the variables will fix the issue you are encountering with the exception not being defined. The logic that was put in place was put there because sometimes the browsers are not very nice with what they give during exceptions.  

Thanks for logging this, and I will take a deeper look later.

**Comment by rigoneri** [comment]
Cool, For now I just changed that if statement to be:
```
if (!exception || exception.stack === null)
```
Since all other params are defined and we can figure out the issue based one the `message` param...

**Comment by garrypolley** [comment]
Thanks for the suggestion here. I'm going to take a look at this tonight and see how to make it work a little better.

**Comment by garrypolley** [comment]
This should hopefully get resolved with #7. Let me know if that doesn't work for you.

**Comment by garrypolley** [comment]
I assume this is resolved. I'm going to close this out given that #7 has been merged and released.
